apiVersion: apps/v1
kind: Deployment
metadata:
  name: scala-app-jvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scala-app-jvm
  template:
    metadata:
      labels:
        app: scala-app-jvm
    spec:
      containers:
        - name: scala-app-jvm
          image: scala-app-jvm:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: APP_LABEL
              value: {{ .Values.label }}
        
