apiVersion: v1
kind: Service
metadata:
  name: scala-app-jvm  
spec:
  selector:
    app: scala-app-jvm  
  ports:
    - port: {{ .Values.port }}  # 👈 Port exposed inside cluster
      targetPort: 8080
      protocol: TCP
