apiVersion: v1
kind: Service
metadata:
  name: prometheus  
spec:
  selector:
    app: prometheus  
  ports:
    - port: {{ .Values.service.port }}  # 👈 Port exposed inside cluster
      targetPort: 9090
      protocol: TCP
