version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123
    networks:
      - monitoring
    volumes:
      - ./grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/provisioning/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana

  scala-app-jvm:
    image: scala-app-jvm
    build:
      context: ./scala-app
      dockerfile: "./jvm.Dockerfile"
    environment:
      - APP_PORT=8080
      - APP_LABEL=jvm
      - JAVA_TOOL_OPTIONS=-XX:StartFlightRecording=duration=10m,filename=/app/scala-app.jfr -XX:+AlwaysActAsServerClassMachine -Xmx2g -Xms2g
    ports:
      - "8080:8080"
    cpus: 0.5
    mem_limit: 3g
    networks:
      - monitoring

  scala-app-native:
    image: scala-app-native
    build:
      context: ./scala-app
      dockerfile: "./graal.Dockerfile"
    environment:
      - APP_PORT=8082
      - APP_LABEL=native
    ports:
      - "8082:8082"
    cpus: 0.5
    mem_limit: 1g
    networks:
      - monitoring

  scala-app-crac:
    image: scala-app-crac
    environment:
      - APP_PORT=8084
      - APP_LABEL=crac
    ports:
      - "8084:8084"
    cpus: 0.5
    mem_limit: 3g
    networks:
      - monitoring

  go-app:
    image: go-app
    build:
      context: ./go-app
      dockerfile: "./Dockerfile"
    environment:
      - APP_PORT=8083
    ports:
      - "8083:8083"
    cpus: 0.5
    mem_limit: 1g
    networks:
      - monitoring

  scala-app-client:
    build:
      context: ./client
      dockerfile: "./Dockerfile"
    environment:
      - TARGET_APP_HOST=scala-app-jvm
      - TARGET_APP_PORT=8080
      - TARGET_LOAD_RPS=100
    cpus: 0.5
    mem_limit: 1g
    networks:
      - monitoring

  scala-app-native-client:
    build:
      context: ./client
      dockerfile: "./Dockerfile"
    environment:
      - TARGET_APP_HOST=scala-app-native
      - TARGET_APP_PORT=8082
      - TARGET_LOAD_RPS=100
    cpus: 0.5
    mem_limit: 1g
    networks:
      - monitoring


  scala-app-crac-client:
    build:
      context: ./client
      dockerfile: "./Dockerfile"
    environment:
      - TARGET_APP_HOST=scala-app-crac
      - TARGET_APP_PORT=8084
      - TARGET_LOAD_RPS=100
    cpus: 0.5
    mem_limit: 1g
    networks:
      - monitoring


  go-app-client:
    build:
      context: ./client
      dockerfile: "./Dockerfile"
    environment:
      - TARGET_APP_HOST=go-app
      - TARGET_APP_PORT=8083
      - TARGET_LOAD_RPS=100
    cpus: 0.5
    mem_limit: 1g
    networks:
      - monitoring

networks:
  monitoring:
    external: true

volumes:
  grafana-data:
