version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123
    networks:
      - monitoring
    volumes:
      - ./grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/provisioning/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana

  scala-app:
    image: scala-app
    build:
      context: ./scala-app
      dockerfile: "./Dockerfile"
    environment:
      - APP_PORT=8080
      - JAVA_TOOL_OPTIONS=-XX:StartFlightRecording=duration=10m,filename=/app/scala-app.jfr -XX:+AlwaysActAsServerClassMachine -Xmx2g -Xms2g
      # -Xlog:compilation*=debug
    ports:
      - "8080:8080"
    cpus: 2
    mem_limit: 3g
    networks:
      - monitoring

  go-app:
    image: go-app
    build:
      context: ./go-app
      dockerfile: "./Dockerfile"
    environment:
      - APP_PORT=8081
    ports:
      - "8081:8081"
    cpus: 2
    mem_limit: 1g
    networks:
      - monitoring

  scala-app-client:
    build:
      context: ./client
      dockerfile: "./Dockerfile"
    environment:
      - TARGET_APP_HOST=scala-app
      - TARGET_APP_PORT=8080
      - TARGET_LOAD_RPS=100
    cpus: 0.5
    mem_limit: 1g
    networks:
      - monitoring

  go-app-client:
    build:
      context: ./client
      dockerfile: "./Dockerfile"
    environment:
      - TARGET_APP_HOST=go-app
      - TARGET_APP_PORT=8081
      - TARGET_LOAD_RPS=100
    cpus: 0.5
    mem_limit: 1g
    networks:
      - monitoring

networks:
  monitoring:
    external: true

volumes:
  grafana-data:
