prometheus:
  service:
    port: 9090

grafana:
  adminPassword: '123'
  service:
    port: 3000

scala-app:
  jvm:
    port: 8080
    cpu: '0.5'
    label: jvm
    memory: '3Gi'
  native:
    port: 8082
    label: native
    cpu: '0.5'
    memory: '1Gi'

go-app:
  port: 8083
  cpu: '0.5'
  memory: '1Gi'

clients:
  - name: scala-app-client
    target_host: scala-app-jvm
    target_port: 8080

  - name: scala-app-native-client
    target_host: scala-app-native
    target_port: 8082

  - name: go-app-client
    target_host: go-app
    target_port: 8083
