ARG BASE_IMAGE=ubuntu:24.04
ARG JDK_NAME=zulu17.56.15-ca-crac-jdk17.0.14-linux_x64

FROM  $BASE_IMAGE

ARG JDK_NAME
ENV JAVA_HOME=/usr/share/$JDK_NAME

RUN apt-get update && apt-get install -y wget
RUN wget -O crac-jdk.tar.gz https://cdn.azul.com/zulu/bin/$JDK_NAME.tar.gz
RUN tar zxf ./crac-jdk.tar.gz -C /usr/share

RUN ln -s $JAVA_HOME/bin/java /bin/ && ln -s $JAVA_HOME/bin/jcmd /bin/
ADD target/cr /cr
ADD target/scala-app.jar /crac.jar


ENTRYPOINT [ "java", "-XX:CRaCRestoreFrom=/cr" ]
