apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: course-project-go-app
          ports:
            - containerPort: '{ { .Values.go-app.port } }'
          env:
            - name: APP_PORT
              value: '{{ .Values.port}}'
